User profile#2
HibyteIntern/internal-betting-fe pull request #25
Opened 2024-01-15 15:48 UTC by AvrAlexandra

2024-01-16 13:42 UTC, DrBaxR requested changes

2024-01-16 13:42 UTC, DrBaxR commented on src/app/components/user-profile-form/user-profile-form.component.ts
> +          console.log(this.originalUserProfile);
remove console log

2024-01-16 13:42 UTC, DrBaxR commented on src/app/components/user-profile/user-profile.component.html
> +<router-outlet></router-outlet>
newline

2024-01-16 13:42 UTC, DrBaxR commented on src/app/shared/components/loading-spinner/loading-spinner.component.scss
> +
newline

2024-01-16 13:42 UTC, DrBaxR commented on src/app/shared/components/loading-spinner/loading-spinner.component.ts
> +    '<div class="lds-ring"><div></div><div></div><div></div><div></div></div>',
Why not use the angular material spinner component?

2024-01-23 16:28 UTC, DrBaxR approved these changes

2024-01-23 20:30 UTC, DanceaRadu requested changes

2024-01-23 20:30 UTC, DanceaRadu commented on src/styles.scss
>  }
The **.select-dropdown** styling should not be removed. Also, the **h1** styling is duplicated. Remove the h1 styling and keep the .select-dropdown.

2024-01-23 20:30 UTC, DanceaRadu commented on src/app/shared/components/loading-spinner/loading-spinner.component.spec.ts
The .spec files can be removed since we're not doing any testing (for now). You should probably remove every other .spec file in this PR.

2024-01-23 20:30 UTC, DanceaRadu commented on src/app/shared/components/loading-spinner/loading-spinner.component.ts
The rest of the website is not using this spinner. You could delete this spinner, and use the **lds-spinner** class from the global styles instead.

2024-01-23 20:30 UTC, DanceaRadu commented on src/app/service/user-profile.service.ts
> -      //console.log(this.userProfileSubject.value);
Remove this comment.

2024-01-23 20:30 UTC, DanceaRadu commented on src/app/app.component.ts
A lot of imports in this file are unused. You could remove them.

2024-01-23 20:30 UTC, DanceaRadu commented on src/app/components/bets-list/bets-list.component.ts
A lot of imports in this file are unused. You could remove them.

2024-01-23 20:30 UTC, DanceaRadu commented on src/app/components/competitions/competitions.component.html
Duck ?

2024-01-24 12:19 UTC, AvrAlexandra commented on src/app/components/competitions/competitions.component.html
It's not my component

2024-01-26 13:26 UTC, DanceaRadu approved these changes

2024-01-26 13:26 UTC, merged