Crud competitions #4
HibyteIntern/internal-betting-fe pull request #26
Opened 2024-01-16 10:51 UTC by Serban681

Added index page, view competition page, update competition page, and create competition page #5

2024-01-16 15:10 UTC, DrBaxR requested changes

2024-01-16 15:10 UTC, DrBaxR commented on src/app/components/competitions/competition-card/competition-card.component.ts
> +  emitViewClick() {
I would get rid of these methods and just emit the events directly from the HTML template

2024-01-16 15:10 UTC, DrBaxR commented on src/app/components/competitions/view-competition/view-competition.component.ts
> +          console.log(this.competition?.events);
remove console log

2024-01-16 15:10 UTC, DrBaxR commented on src/app/components/event-card/event-card.component.ts
> +  emitViewClick() {
same thing with the events here

2024-01-18 10:59 UTC, DrBaxR approved these changes

2024-01-22 13:01 UTC, DanceaRadu approved these changes

2024-01-22 13:01 UTC, merged