Event interaction#4
HibyteIntern/internal-betting-fe pull request #29
Opened 2024-01-18 13:44 UTC by MarcAndreiFurtos

2024-01-23 10:14 UTC, DrBaxR requested changes

2024-01-23 10:14 UTC, DrBaxR commented on src/app/components/events/create-event/create-event.component.ts
> +    this.http.get<UserProfile[]>('http://localhost:8080/api/user-profiles').subscribe(
Don't directly inject http client into component, please use method from user profile service or create a method these in case it doesn't exist

2024-01-23 10:14 UTC, DrBaxR commented on src/app/components/events/create-event/create-event.component.ts
> +    console.log('Form Data:', this.formData);
Remove console.log

2024-01-23 10:14 UTC, DrBaxR commented on src/app/components/events/create-event/create-event.component.ts
> +        console.log('Event added successfully:', response);
remove console.log

2024-01-23 10:14 UTC, DrBaxR commented on src/app/components/events/edit-event/edit-event.component.ts
> +      this.http
Please make separate service for making http requests for events

2024-01-23 10:14 UTC, DrBaxR commented on src/app/components/events/edit-event/edit-event.component.ts
> +    this.http
Move request to service

2024-01-23 10:14 UTC, DrBaxR commented on src/app/components/events/view-event/view-event.component.ts
> +    this.http.get(`http://localhost:8080/api/v1/events/get/${this.eventId}`).subscribe(
Move to service

2024-01-23 10:14 UTC, DrBaxR commented on src/app/entity/Bet.ts
Please rename file to `bet.model.ts`

2024-01-23 10:14 UTC, DrBaxR commented on src/app/entity/CompleteBetType.ts
Please rename file to `complete-bet-type.model.ts`

2024-01-23 10:14 UTC, DrBaxR commented on src/app/entity/EventRequest.ts
> +export class EventRequest {
For consistency, I recommend the data models be either all `class` or all `interface` (for example, `CompleteBetType` is an interface). I generally think that interfaces are easier to work with, so please change this and any other model classes in this PR to interface

2024-01-23 10:14 UTC, DrBaxR commented on src/app/entity/EventRequest.ts
Please rename file to `event-request.model.ts`

2024-01-23 10:14 UTC, DrBaxR commented on src/app/entity/Status.ts
rename to `status.enum.ts`

2024-01-23 10:14 UTC, DrBaxR commented on src/app/entity/UserProfile.ts
rename and change to interface

2024-01-23 10:14 UTC, DrBaxR commented on src/app/service/event.service.ts
> +  addEvent(eventRequest: EventRequest): Observable<any> {
Does this have to return an observable of `any`? If not, please strongly type what the observable contains

2024-01-23 10:14 UTC, DrBaxR commented on src/app/service/event.service.ts
> +  private addUrl = 'http://localhost:8080/api/v1/events/add';
It's a good idea to move the base URL (in this case `http://localhost:8080`) to the `environment.ts` file, so it can be easily changed

2024-01-23 10:14 UTC, DrBaxR commented on src/app/service/user-profile.service.ts
>              console.log('Failed to update user profile.');
Remove console.log

2024-01-23 10:14 UTC, DrBaxR commented on src/app/service/user-profile.service.ts
>        //console.log(this.userProfileSubject.value);
delete commented code

2024-02-02 15:58 UTC, DrBaxR approved these changes

2024-02-02 16:07 UTC, DanceaRadu approved these changes

2024-02-02 16:07 UTC, merged