User group#10
HibyteIntern/internal-betting-fe pull request #34
Opened 2024-01-29 12:09 UTC by ambragoanta

@DanceaRadu @Serban681 we need to make some changes in the autocomplete component

2024-02-09 13:37 UTC, DrBaxR requested changes

2024-02-09 13:37 UTC, DrBaxR commented on src/app/components/user-groups/group-form/group-form.component.ts
> +  ngOnInit(): void {
Please move ngoninit above ngonchanges

2024-02-09 13:37 UTC, DrBaxR commented on src/app/components/user-groups/group-form/group-form.component.ts
> +  displayProfileImage(blob: Blob) {
Use same extracted method here

2024-02-09 13:37 UTC, DrBaxR commented on src/app/components/user-groups/group/group.component.ts
> +  private displayGroupImage(blob: Blob) {
Use same extracted method

2024-02-09 13:37 UTC, DrBaxR commented on src/app/components/user-groups/groups/groups.component.ts
> +    this.groupService.getAll().subscribe((data) => {
use the `async` pipe instead

2024-02-09 13:37 UTC, DrBaxR commented on src/app/components/user-profile-form/user-profile-form.component.ts
> +  displayProfileImage(blob: Blob) {
use extracted method

2024-02-09 13:37 UTC, DrBaxR commented on src/app/service/user-profile.service.ts
> +  userProfileUrl = 'http://localhost:8080/api/v1/user-profile';
extract base url to environment file/use it here if it already exists

2024-02-22 11:51 UTC, DrBaxR approved these changes

2024-02-22 11:59 UTC, DanceaRadu approved these changes

2024-02-22 11:59 UTC, merged